---
- name: create Prometheus group
  group:
    name: '{{ prometheus_bind_exporter_group }}'
    state: present

- name: create Prometheus user
  user:
    name: "{{ prometheus_bind_exporter_user }}"
    group: "{{ prometheus_bind_exporter_group }}"
    createhome: no
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for prometheus and bind_exporter
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_bind_exporter_user }}"
    group: "{{ prometheus_bind_exporter_group }}"
    mode: 0750
  loop:
    - "{{ prometheus_bind_exporter_install_path }}"
    - "{{ prometheus_bind_exporter_config_path }}"
    - "{{ prometheus_bind_exporter_subdir }}"

- name: download bind_exporter binary
  get_url:
    url: "{{ prometheus_bind_exporter_url }}"
    dest: "{{ prometheus_bind_exporter_subdir }}/bind_exporter"
    owner: '{{ prometheus_bind_exporter_user }}'
    group: '{{ prometheus_bind_exporter_group }}'
    mode: 0755
    checksum: '{{ prometheus_bind_exporter_checksum }}'
  notify:
    - restart bind_exporter

- name: copy bind_exporter systemd profile
  template:
    src: 'bind_exporter.service.j2'
    dest: '/lib/systemd/system/bind_exporter.service'
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd reload
    - restart bind_exporter

- name: copy bind_exporter config
  template:
    src: 'bind_exporter.defaults.j2'
    dest: '/etc/default/bind_exporter'
    owner: '{{ prometheus_bind_exporter_user }}'
    group: '{{ prometheus_bind_exporter_group }}'
    mode: 0640
  notify:
    - restart bind_exporter

- name: bind_exporter systemd service enable
  systemd:
    name: bind_exporter
    state: started
    enabled: yes

...
