---

- name: install prometheus bind_exporter
  include: install.yaml
  tags:
    - prometheus
    - bind_exporter

- name: ufw | open access to bind_exporter
  include: ufw.yaml
  when: enable_ufw
  tags:
    - prometheus
    - bind_exporter
    - ufw
