---
- name: include ufw role
  include_role:
    name: ufw

- name: enable ufw for bind_exporter
  ufw:
    comment: 'Prometheus bind_exporter'
    rule: allow
    src: '{{ item }}'
    proto: tcp
    port: '{{ prometheus_bind_exporter_listen_port }}'
    direction: in
  loop: '{{ prometheus_bind_exporter_src_access }}'
