---
# handlers file for bind_exporter

- name: restart bind_exporter
  systemd:
    name: bind_exporter
    state: restarted
    daemon_reload: yes
  tags:
    - prometheus
    - bind_exporter

- name: systemd reload
  systemd:
    daemon_reload: yes
  tags:
    - prometheus
    - bind_exporter
...
